1. Write down the characteristic equation for matrix $A = \begin{bmatrix}
3 & 2\\
5 & 3\\
\end{bmatrix}$. 

1) 
    $ \lambda^2 -6 \lambda -1 = 0 $

2. Using the above characteristic equation to solve for eigenvalues and eigenvectors for matrix $A$. 

In [1]:
import numpy as np
from numpy.linalg import eig

a,b,c = 1, -6, -1

eig1 = (-b+np.sqrt(b**2-4*a*c))/(2*a)
eig2 = (-b-np.sqrt(b**2-4*a*c))/(2*a)


print("The eigenvalues are %.2f and %.2f" %(eig1,eig2))

values,vectors = eig(np.array([[3,2],
                              [5,3]]))

print("The eigenvectors are:")
print(vectors[0])
print(vectors[1])

The eigenvalues are 6.16 and -0.16
The eigenvectors are:
[ 0.53452248 -0.53452248]
[0.84515425 0.84515425]


3. Using the first eigenvector derived from problem 2 to verify that $Ax = \lambda{x}$. 

In [2]:
0.53452248/np.sqrt(0.53452248**2+0.53452248**2)*np.sqrt(2)

1.0

In [3]:
A = np.array([[3,2],
             [5,3]])

eigval,eigvec = eig(A)
x = np.array([[1/np.sqrt(2)],
             [-1/np.sqrt(2)]])
print("Eigenvalue 1")
print(np.dot(A,x))
print(eigval[0]*x)
print("Eigenvalue 2")
print(eigvec[0].T)

eigvec[0]

Eigenvalue 1
[[0.70710678]
 [1.41421356]]
[[ 4.35738832]
 [-4.35738832]]
Eigenvalue 2
[ 0.53452248 -0.53452248]


array([ 0.53452248, -0.53452248])

4. Get the largest eigenvalue and eigenvector for matrix $A = \begin{bmatrix}
2 & 1 & 2\\
1 & 3 & 2\\
2 & 4 & 1\\
\end{bmatrix}$ using the power method. You can start with initial vector [1, 1, 1], see what you will get after 8 iterations. 

In [4]:
A = np.array([[2,1,2],
             [1,3,2],
             [2,4,1]])

v = np.array([[1],
             [1],
             [1]])


for i in range(8):
    eigen = max(np.matmul(A,v))[0]
    if eigen != 0:
        v = np.matmul(A,v)/eigen
    
print("Largest eigenvalue: %.2f" %eigen)
print("Associated eigenvector:")
print(v)

Largest eigenvalue: 6.03
Associated eigenvector:
[[0.71918849]
 [0.8976852 ]
 [1.        ]]


5. Do a QR decomposition for matrix $A$ in problem 4, and verify that $A=QR$ and $Q$ is an orthogonal matrix. 

In [5]:
from numpy.linalg import qr

q,r = qr(A)
print("A = QR")
print(np.dot(q,r))
print("Q")
print(q)
print("Q transpose x Q inverse")
print(np.dot(q.T,np.linalg.inv(q)))

A = QR
[[2. 1. 2.]
 [1. 3. 2.]
 [2. 4. 1.]]
Q
[[-0.66666667  0.7028635  -0.24806947]
 [-0.33333333 -0.57882876 -0.74420841]
 [-0.66666667 -0.41344912  0.62017367]]
Q transpose x Q inverse
[[ 0.37553626  0.91130408  0.1688117 ]
 [-0.77284917  0.40844721 -0.48566968]
 [-0.51154343  0.05192059  0.85768734]]


6. Use the QR method to get all the eigenvalues for matrix $A$ in problem 4. 

In [6]:
from numpy.linalg import qr
for i in range(100):
    q,r = qr(A)
    A = np.dot(r,q)

print("The eigenvalues are %.4f, %.4f and %.4f" %(A[0][0],A[1][1],A[2][2]))

The eigenvalues are 6.0291, 0.6662 and -0.6953


7. Get the eigenvalues and eigenvectors for the matrix $A$ in problem 4 using the Python built-in function. 

In [7]:
from numpy.linalg import eig
values,vectors = eig(A)

print("Eigenvalues:")
print(values)
print("Eigenvectors:")
print(vectors)

Eigenvalues:
[ 6.02911192 -1.36536788  1.33625596]
Eigenvectors:
[[ 1.         -0.18910254  0.10850537]
 [ 0.          0.35457859 -0.75679012]
 [ 0.         -0.91570424 -0.64458924]]


In [8]:
eig(A)

EigResult(eigenvalues=array([ 6.02911192, -1.36536788,  1.33625596]), eigenvectors=array([[ 1.        , -0.18910254,  0.10850537],
       [ 0.        ,  0.35457859, -0.75679012],
       [ 0.        , -0.91570424, -0.64458924]]))